build:
  image: xataz/drone-docker:1.9.1
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /home/docker/.docker/config.json:/root/.docker/config.json
  commands:
    - chmod +x build.sh
    - ./build.sh push
